services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - s3ninja
    networks:
      - bonusx-network

  postgres:
    hostname: database.local
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bonusx-network

  s3ninja:
    hostname: storage.local
    image: scireum/s3-ninja:latest
    platform: linux/amd64
    expose:
      - '9000'
    volumes:
      - ./docker/storage_data:/home/sirius/data
    networks:
      - bonusx-network

volumes:
  postgres_data:
  s3ninja_data:

networks:
  bonusx-network:
    driver: bridge
